export const USER = {
  AJAX_BEGIN: 'USER_AJAX_BEGIN',
  AJAX_END: 'USER_AJAX_END',
  LOGIN: 'USER_LOGIN',
  LOGOUT: 'USER_LOGOUT'
}

export const PLATFORMS = {
  AJAX_BEGIN: 'PLATFORMS_AJAX_BEGIN',
  AJAX_END: 'PLATFORMS_AJAX_END',
  CLEAR_ALL: 'PLATFORMS_CLEAR_ALL',
  FETCH_SUCCESS: 'PLATFORMS_FETCH_SUCCESS',
  CREATE_SUCCESS: 'PLATFORMS_CREATE_SUCCESS',
  UPDATE_SUCCESS: 'PLATFORMS_UPDATE_SUCCESS',
  DELETE_SUCCESS: 'PLATFORMS_DELETE_SUCCESS'
}

export const GAMES = {
  AJAX_BEGIN: 'GAMES_AJAX_BEGIN',
  AJAX_END: 'GAMES_AJAX_END',
  CLEAR_ALL: 'GAMES_CLEAR_ALL',
  FETCH_SUCCESS: 'GAMES_FETCH_SUCCESS',
  CREATE_SUCCESS: 'GAMES_CREATE_SUCCESS',
  UPDATE_SUCCESS: 'GAMES_UPDATE_SUCCESS',
  DELETE_SUCCESS: 'GAMES_DELETE_SUCCESS'
}
